import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const Outfitfont = Outfit({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap"
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Outfitfont.className} antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
